---
application:
  name: "pantherbot"
  project: "PantherBot"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "MySQL"
  version: "8.0"
routers:
- name: "main-pantherbot"
  routes:
  - application_name: "pantherbot"
    paths:
    - "/*"
